# -*- coding: utf-8 -*-
"""last_ML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvPFqNBqUkkWrDgMP00V5H2IXm9-CQIN
"""

import tensorflow as tf
import cv2
import numpy as np
import pickle
import sys
# from google.colab import drive
# drive.mount('/content/drive')

# import os
# os.environ['KAGGLE_CONFIG_DIR'] = "/content/drive/My Drive/Kaggle"
# %cd /content/drive/My Drive/Kaggle

base_model =tf.keras.applications.InceptionV3(
                include_top=False,
                weights=None,
                input_tensor=None,
                input_shape=(224,224,3),
                pooling='avg',
                classes=1000,
                classifier_activation="softmax",
               )
x=base_model.output
x = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(inputs = base_model.input, outputs = x)

infile = open("weightsCovid",'rb')
weights_update = pickle.load(infile)
infile.close()

model.set_weights(weights=weights_update)

#img = cv2.imread('/content/drive/MyDrive/Kaggle/COVID-19_Radiography_Dataset/Normal/Normal-100.png')/255 
#img = cv2.imread('/content/drive/MyDrive/Kaggle/COVID-19_Radiography_Dataset/COVID/COVID-1001.png')/255 
img = cv2.imread(sys.argv[1])/255 
img_modify_size = cv2.resize(img,(224,224))
img_modify_shape = img_modify_size.reshape(1,224,224,3)
result = model(img_modify_shape)
a ,b ,c = result[0][0].numpy(),result[0][1].numpy(),result[0][2].numpy()
per_viral, per_covid, per_normal = a*100, b*100, c*100
answer = max(per_viral,per_covid,per_normal)
if answer == per_viral:
  print("Virual with accuarcy = ",per_viral)
elif answer == per_covid:
  print("covid with accuarcy = ",per_covid)
else:  
  print("normal with accuarcy = ",per_normal)